// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package navigator_public_cats

import ()

type NavigatorPublicCat struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	HasImage bool   `json:"has_image"`
	Visible  bool   `json:"visible"`
	OrderNum int32  `json:"order_num"`
}
