// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package navigator_public_cats

import (
	"context"
)

const ListNavigatorPublicCategories = `-- name: ListNavigatorPublicCategories :many
SELECT id, name, has_image, visible, order_num FROM navigator_public_cats
`

func (q *Queries) ListNavigatorPublicCategories(ctx context.Context) ([]NavigatorPublicCat, error) {
	rows, err := q.db.QueryContext(ctx, ListNavigatorPublicCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NavigatorPublicCat{}
	for rows.Next() {
		var i NavigatorPublicCat
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HasImage,
			&i.Visible,
			&i.OrderNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
