// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package users_stats

import (
	"context"
	"database/sql"
)

type Querier interface {
	GetUserStats(ctx context.Context, userID int32) (UsersStat, error)
	InsertUserStats(ctx context.Context, userID int32) (sql.Result, error)
	ListUserStats(ctx context.Context) ([]UsersStat, error)
	UpdateBubbleChat(ctx context.Context, arg UpdateBubbleChatParams) error
}

var _ Querier = (*Queries)(nil)
