// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package bubbles_chat

import (
	"context"
)

type Querier interface {
	GetBubbleChatById(ctx context.Context, id int32) (BubblesChat, error)
	GetBubbleChatByKey(ctx context.Context, key string) (BubblesChat, error)
	ListsBubbleChat(ctx context.Context) ([]BubblesChat, error)
}

var _ Querier = (*Queries)(nil)
