// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: query.sql

package navigator_flat_cats

import (
	"context"
)

const ListNavigatorFlatCategories = `-- name: ListNavigatorFlatCategories :many
SELECT id, min_rank, caption_save, caption, allow_trade, max_users, is_public, order_num FROM navigator_flat_cats ORDER BY id DESC
`

func (q *Queries) ListNavigatorFlatCategories(ctx context.Context) ([]NavigatorFlatCat, error) {
	rows, err := q.db.QueryContext(ctx, ListNavigatorFlatCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NavigatorFlatCat{}
	for rows.Next() {
		var i NavigatorFlatCat
		if err := rows.Scan(
			&i.ID,
			&i.MinRank,
			&i.CaptionSave,
			&i.Caption,
			&i.AllowTrade,
			&i.MaxUsers,
			&i.IsPublic,
			&i.OrderNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
