// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package room_models

import (
	"context"
)

type Querier interface {
	GetModelById(ctx context.Context, id int32) (RoomModel, error)
	GetModelByName(ctx context.Context, name string) (RoomModel, error)
	ListRoomModels(ctx context.Context) ([]RoomModel, error)
}

var _ Querier = (*Queries)(nil)
