CREATE TABLE `rooms`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `owner_id` int NOT NULL DEFAULT 0,
  `name` varchar(50) NOT NULL DEFAULT '',
  `description` varchar(512) NOT NULL DEFAULT '',
  `model_id` int NOT NULL DEFAULT 1,
  `password` varchar(20) NOT NULL DEFAULT '',
  `state` ENUM('open','locked','password','invisible') NOT NULL DEFAULT 'open',
  `users` int NOT NULL DEFAULT 0,
  `max_users` int NOT NULL DEFAULT 25,
  `flat_category_id` int NOT NULL DEFAULT 1,
  `score` int NOT NULL DEFAULT 0,
  `floorpaper` varchar(5) NOT NULL DEFAULT '0.0',
  `wallpaper` varchar(5) NOT NULL DEFAULT '0.0',
  `landscape` varchar(5) NOT NULL DEFAULT '0.0',
  `wall_thickness` int NOT NULL DEFAULT 0,
  `wall_height` int NOT NULL DEFAULT -1,
  `floor_thickness` int NOT NULL DEFAULT 0,
  `tags` varchar(500) NOT NULL DEFAULT '',
  `is_public` BOOLEAN NOT NULL DEFAULT FALSE,
  `is_staff_picked` BOOLEAN NOT NULL DEFAULT FALSE,
  `allow_other_pets` BOOLEAN NOT NULL DEFAULT FALSE,
  `allow_other_pets_eat` BOOLEAN NOT NULL DEFAULT FALSE,
  `allow_walkthrough` BOOLEAN NOT NULL DEFAULT TRUE,
  `is_wall_hidden` BOOLEAN NOT NULL DEFAULT FALSE,
  `chat_mode` int NOT NULL DEFAULT 0,
  `chat_weight` int NOT NULL DEFAULT 1,
  `chat_scrolling_speed` int NOT NULL DEFAULT 1,
  `chat_hearing_distance` int NOT NULL DEFAULT 50,
  `chat_protection` int NOT NULL DEFAULT 2,
  `who_can_mute` int NOT NULL DEFAULT 0,
  `who_can_kick` int NOT NULL DEFAULT 0,
  `who_can_ban` int NOT NULL DEFAULT 0,
  `roller_speed` int NOT NULL DEFAULT 4,
  `is_promoted` BOOLEAN NOT NULL DEFAULT FALSE,
  `trade_mode` int NOT NULL DEFAULT 2,
  `move_diagonal` BOOLEAN NOT NULL DEFAULT TRUE,
  `is_wired_hidden` BOOLEAN NOT NULL DEFAULT FALSE,
  `is_forsale` BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id),
  FOREIGN KEY (owner_id) REFERENCES users (id),
  FOREIGN KEY (model_id) REFERENCES room_models (id),
  FOREIGN KEY (flat_category_id) REFERENCES navigator_flat_cats (id)
);